### ISSUE TITLE
Variant: Replace "Chromosome" with other sequence identifier

### ISSUE THREAD

**Issue by mbaudis** [ga4gh-beacon/specification-v2-default-schemas#9]
It had been determined a long time ago that Beacon should move away from "Chromosome", to be able to represent non-human sequences etc.

* https://github.com/ga4gh-beacon/specification-v2/blob/master/beacon.yaml#L630https://github.com/ga4gh-beacon/specification-v2-default-schemas/blob/develop/default_variant_schema.yaml#L21
* https://github.com/ga4gh-beacon/specification-v2/blob/master/beacon.yaml#L630

Also, it seems sensible to have a modular approach where this is defined once for all use cases (Beacon API & schemas ...). Option: start to define such components directly in SchemaBlocks & reference them.

**Comment by KyleGao** [comment]
For several times, people that are interested in implementing a Beacon have asked/complained to me about its complexity.  For this to become a general spec instead of human specific, I suggest to loose the definition of Chromosome to a string.

Keeping the current rigorous definition would significantly increase the complexity and hinder the compatibility of the spec.
Although people abuse chromosome names (chr12 | 12 | chro12 | etc),  users understand the different conventions within the context of a species, and the problem usually can be easier handled at the implementation level. 

Furthermore, there is also a technical limitation of the current definition. The latest genome assemblies are not linear anymore, and there are other names besides (1-22, X, Y). It would be challenging to keep up with the updates of all assemblies.

**Comment by mbaudis** [comment]
I second that. We will have the need to document allowed values for many different parts of Beacon (recommended ontologies etc.) and then will have `service-info` or such mechanisms to report back about which values are being used by an individual resource.

Also: `chromosome` and `Chromosome` are factually wrong for e.g. viral sequences; the original `referenceName` was better suited (also avoiding `...id` discussions).

**Comment by jrambla** [comment]
If I'm reading your comments correctly, you are saying "change it, but don't change it" ;-)
Which is/are the actual suggestion/s? 
1. To use `referenceName` instead of `chromosome`?
2. Remove the enumeration and allow freedom for that parameter?
3. Use "chr" conversion to reference name at the UI?

**Comment by jrambla** [comment]
Hopefully we have solved that in Beacon v2 Model draft4.
